### ISSUE TITLE
Please change the name of the project since this project isn't related to Prerender.io

### ISSUE THREAD

**Issue by thoop** [bosondata/chrome-prerender#1]
Hi there! Cool project. Could you change the name to something other than "prerender"? I know we're going to get lots of support tickets with people trying to use this project instead of our official [Prerender](https://github.com/prerender/prerender) server.

I would help us out if you could change the name of your project since this project is not related to our Prerender server.

I really appreciate it.

**Comment by messense** [comment]
Sure thing, I would consider to change it to `prerender-py` or `prerender-python`, what do you think?

Also I think `prerender` is somehow a very common name for such task, it would not be fair if you ask me to change that part.

**Comment by thoop** [comment]
Yes, I agree but when you post on our github issues linking to your repo of the same name, it makes it seem less of a common name and more of using the same name :)

**Comment by messense** [comment]
Renamed project name to `chrome-prerender`, also updated the link in that issue.
