### ISSUE TITLE
Useragent compatability with nodejs prerender

### ISSUE THREAD

**Issue by Nyoroon** [bosondata/chrome-prerender#15]
Current user agent is default chrome user agent.
Some configurations of web-servers require "Prerender" in user agent string to work correctly. It's possible to change user agent from chrome-prerender?

**Comment by Nyoroon** [comment]
Example config https://gist.github.com/thoop/8165802

**Comment by messense** [comment]
There is a [`set_user_agent`](https://github.com/bosondata/chrome-prerender/blob/master/prerender/chromerdp.py#L196) method, it's unused for now.

Chrome supports `--user-agent` argument on command line to override default `user-agent` but it seems that it's not working together with `--headless` last time I checked.
