### ISSUE TITLE
Subdirs in S3 storage is always same

### ISSUE THREAD

**Issue by Nyoroon** [bosondata/chrome-prerender#23]
Subdirs in S3 storage is always same. (first 4 chars of `url` is always `http`)
```
        hex_name = codecs.encode(url.encode('utf-8'), 'hex').decode('utf-8')
        sub_dir = os.path.join(hex_name[:2], hex_name[2:4])
```
Maybe make hash of URL or take URI instead of URL?

**Comment by messense** [comment]
Thank you for reporting this, would you like to fix it?

**Comment by Nyoroon** [comment]
Okay, i'll try.
