### ISSUE TITLE
Remove <meta name="fragment"... from prerendered pages

### ISSUE THREAD

**Issue by Nyoroon** [bosondata/chrome-prerender#25]
We need to remove `<meta name="fragment" content="!">` from prerendered pages because some bots doesn't like it.
https://yandex.ru/support/webmaster/robot-workings/ajax-indexing.html?lang=en

**Comment by Nyoroon** [comment]
I can make pull request, but i'm not sure about structure of application :(

**Comment by messense** [comment]
I don't think you should add `<meta name="fragment" content="!">` to your HTML in the first place when you choose to use prerender. That said, it's not our responsibility to remove that.

**Comment by Nyoroon** [comment]
You can't just make list of all bots useragents (and keep it up to date). And bots can care of getting prerendered page (via `_external_fragment_`) themselves.

**Comment by messense** [comment]
I don't think people really care about all the bots? But I'm ok with merging a PR to remove the meta.

**Comment by Nyoroon** [comment]
*\*mumble\** SEO *\*mumble\** optimization *\*mumble\**
😆 

Okay!
