### ISSUE TITLE
Get dockerized

### ISSUE THREAD

**Issue by laosb** [bosondata/chrome-prerender#4]
Good job!

I wish you can publish this in a Docker image with the PR #3, so we can use this simply with Docker.

I'm expecting Headless Chrome in a separated container.

**Comment by messense** [comment]
Maybe adding a `docker-compose.yml` would be a good idea?

**Comment by messense** [comment]
https://hub.docker.com/r/messense/prerender/

**Comment by messense** [comment]
[Dockerfile](https://github.com/bosondata/chrome-prerender/blob/master/Dockerfile)

**Comment by macrozone** [comment]
Can we have this with chrome installed? I have troubles installing prerender on an empty ubuntu server

**Comment by messense** [comment]
@macrozone For dockerized Chrome you can use https://github.com/alpeware/chrome-headless-trunk
